name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - pandas
  - geopandas 
  - folium
  - pysal
  - rtree
  - descartes
  - scipy
  - seaborn
  - scikit-learn
